name: secret hello 
on: 
  push:
jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: print secret 
        env: 
          MESSAGE: ${{ secrets.username }}
        
        run: |
          echo "there is a secret"
